app/views.py
"""Views module."""

# Flask
from flask import Blueprint, abort, redirect, render_template, url_for
from flask_login import current_user, login_required, login_user, logout_user

# Local application
from app.forms import ListForm, SignInForm, TaskForm
from app.models import List, Task, User
from app.plugins import db

app_routes = Blueprint('tasks', __name__)


@app_routes.route('/sign_in/', methods=['GET', 'POST'])
def sign_in():
    """Authenticate a user and start a session."""
    sign_in_form = SignInForm()
    if sign_in_form.validate_on_submit():
        data = sign_in_form.data
        user = User.query.filter_by(username=data['username'], password=data['password']).first()
        if user:
            login_user(user, remember=False)
            return redirect(url_for('tasks.list_lists'))
    context = {
        'sign_in_form': sign_in_form,
    }
    return render_template('sign_in.html', **context)


@app_routes.route('/sign_out/', methods=['POST'])
@login_required
def sign_out():
    """Finish a session."""
    logout_user()
    return redirect(url_for('tasks.sign_in'))


@app_routes.route('/lists/', methods=['GET'])
@login_required
def list_lists():
    """List the lists of the current user."""
    lists = List.query.filter_by(user=current_user)
    context = {
        'current_user': current_user,
        'lists': lists,
    }
    return render_template('lists.html', **context)


@app_routes.route('/lists/new/', methods=['GET', 'POST'])
@login_required
def create_list():
    """Create a new list."""
    list_form = ListForm()
    if list_form.validate_on_submit():
        data = list_form.data
        data.pop('csrf_token')
        data.pop('submit')
        user = current_user
        new_list = List(**data, user=user)
        db.session.add(new_list)
        db.session.commit()
        return redirect(url_for('tasks.list_lists'))

    context = {
        'current_user': current_user,
        'list_form': ListForm()
    }
    return render_template('list_create.html', **context)


@app_routes.route('/lists/<int:list_id>/destroy/', methods=['POST'])
@login_required
def destroy_list(list_id):
    """Delete a list from database."""
    list = List.query.filter_by(id=list_id, user=current_user).first()
    if not list:
        abort(404)
    db.session.delete(list)
    db.session.commit()
    return redirect(url_for('tasks.list_lists'))


@app_routes.route('/lists/<int:list_id>/retrieve/', methods=['GET', 'POST'])
@login_required
def retrieve_list(list_id):
    """Retrieve and allow update details about a list."""
    list = List.query.filter_by(id=list_id, user=current_user).first()
    if not list:
        abort(404)
    list_form = ListForm()

    if list_form.validate_on_submit():
        data = list_form.data
        list.name = data['name']
        list.details = data['details']
        db.session.commit()
        return redirect(url_for('tasks.retrieve_list', list_id=list.id))

    list_form.name.data = list.name
    list_form.details.data = list.details

    context = {
        'current_user': current_user,
        'list': list,
        'list_form': list_form
    }
    return render_template('list_retrieve.html', **context)


@app_routes.route('/lists/<int:list_id>/tasks/<int:task_id>/destroy/', methods=['POST'])
@login_required
def destroy_task(list_id, task_id):
    """Delete a task from database."""
    list = List.query.filter_by(id=list_id, user=current_user).first()
    task = Task.query.filter_by(list=list, id=task_id).first()
    if not task:
        abort(404)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for('tasks.retrieve_list', list_id=list_id))


@app_routes.route('/lists/<int:list_id>/tasks/new/', methods=['GET', 'POST'])
@login_required
def create_task(list_id):
    """Create a list in database."""
    list = List.query.filter_by(id=list_id, user=current_user).first()
    if not list:
        abort(404)
    task_form = TaskForm()

    if task_form.validate_on_submit():
        data = task_form.data
        data.pop('csrf_token')
        data.pop('submit')
        task = Task(**data, list=list)
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('tasks.retrieve_list', list_id=list_id))

    context = {
        'current_user': current_user,
        'list': list,
        'task_form': task_form,
    }
    return render_template('task_create.html', **context)


@app_routes.route('/lists/<int:list_id>/tasks/<int:task_id>/retrieve/', methods=['GET', 'POST'])
@login_required
def retrieve_task(list_id, task_id):
    """Retrieve and allow update details about a task."""
    list = List.query.filter_by(id=list_id, user=current_user).first()
    task = Task.query.filter_by(id=task_id, list=list).first()
    if not task:
        abort(404)
    task_form = TaskForm()
    if task_form.validate_on_submit():
        data = task_form.data
        task.name = data['name']
        task.details = data['details']
        task.due_date = data['due_date']
        task.is_finished = data['is_finished']
        db.session.commit()
        return redirect(url_for('tasks.retrieve_list', list_id=list_id))

    task_form.name.data = task.name
    task_form.details.data = task.details
    task_form.due_date.data = task.due_date
    task_form.is_finished.data = task.is_finished

    context = {
        'current_user': current_user,
        'list': list,
        'task': task,
        'task_form': task_form,
    }
    return render_template('task_retrieve.html', **context)

app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
            <!-- Bootstrap CSS -->
            {{ bootstrap.load_css() }}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        {% endblock %}

        <title>{% block title %}Tasks{% endblock %}</title>
        {% endblock %}
    </head>
    <body>
        <!-- Your page content -->
        {% block content %}{% endblock %}

        {% block scripts %}
            <!-- Optional JavaScript -->
            <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

app/templates/list_create.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{ super() }} | New list {% endblock %}

{% block body %}
{% block content %}
{{ navbar(current_user) }}
<div class="container">
    <br><br>
    <h1 class="h1 fs-3">New list</h1>
    <div class="p-2 flex-grow-1">
        {{ render_form(list_form, method='post', action=url_for('tasks.create_list')) }}
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/list_detail.html
{% extends "base.html" %}

{% block title %} {{super()}} | Lists {% endblock %}

{% block body %}
<form action="/app/lists/new/" method="POST">
    {{ list_form.csrf_token }}
    {{ list_form.name.label }}
    {{ list_form.name }}
    {{ list_form.details.label }}
    {{ list_form.details }}
    {{ list_form.submit }}
</form>
{% endblock %}

app/templates/list_retrieve.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{super()}} | Retrieve list {% endblock %}

{% block body %}
{% block content %}
{{ navbar(current_user) }}
<div class="container">
    <br><br>
    <h1 class="h1 fs-3">List details</h1>
    <div class="p-2 flex-grow-1">
        {{ render_form(list_form, method='post', action=url_for('tasks.retrieve_list', list_id=list.id)) }}
    </div>
    <br><br>

    <div class="d-flex justify-content-between">
        <h1 class="h1 fs-3">Tasks</h1>
        <a class="btn btn-primary" href="{{ url_for('tasks.create_task', list_id=list.id) }}">New task</a>
    </div>
    <br>
    <table class="table">
        <tbody>
            {% for task in list.tasks %}
            <tr>
                <th>
                    {% if task.is_finished %}
                    <a class="ligther fs-6 text-decoration-line-through" href="{{ url_for('tasks.retrieve_task', list_id=list.id, task_id=task.id) }}">{{ task.name }}</a>
                    {% else %}
                    <a class="ligther fs-6 text-decoration-none" href="{{ url_for('tasks.retrieve_task', list_id=list.id, task_id=task.id) }}">{{ task.name }}</a>
                    {% endif %}
                    <p class="fw-lighter">{{ task.details }}</p>
                </th>
                <td>
                    <form action="{{ url_for('tasks.destroy_task', list_id=list.id, task_id=task.id) }}" method="POST">
                        <button class="btn btn-danger" type="submit">Remove</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% endblock %}

app/templates/lists.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{super()}} | Lists {% endblock %}

{% block body %}
{% block content %}
{{ navbar(current_user) }}
<div class="container">
    <br><br>
    <div class="d-flex justify-content-between">
        <h1 class="h1 fs-3">My lists</h1>
        <a class="btn btn-primary" href="{{ url_for('tasks.create_list') }}">New list</a>
    </div>
    <br><br>
    <table class="table">
        <tbody>
            {% for list in lists %}
            <tr>
                <th>
                    <a class="ligther fs-6 text-decoration-none" href="{{ url_for('tasks.retrieve_list', list_id=list.id) }}">{{ list.name }}</a>
                    <p class="fw-lighter">{{ list.details }}</p>
                </th>
                <td>
                    <form class="badge" action="{{ url_for('tasks.destroy_list', list_id=list.id) }}" method="POST">
                        <button class="btn btn-danger" type="submit">Remove</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
{% endblock %}

app/templates/macros.html
{% macro navbar(current_user) %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">My tasks</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('tasks.list_lists') }}">Lists</a>
                </li>
            </ul>
            <form class="d-flex" method="POST" action="{{ url_for('tasks.sign_out') }}">
                <span class="navbar-text">
                    {{ current_user.name }}(@{{current_user.username}}) &nbsp
                </span>
                <span class="navbar-text">
                    |
                </span>
                <button class="btn btn-light" type="submit">Sign out</button>
            </form>
        </div>
    </div>
</nav>
{% endmacro %}

app/templates/sign_in.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{super()}} | Sign In {% endblock %}

{% block body %}
{% block content %}
<div class="container">
    <br><br>
    <h1 class="h1 fs-3">Sign in</h1>
    <div class="p-2 flex-grow-1">
        {{ render_form(sign_in_form, method='post', action=url_for('tasks.sign_in')) }}
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/task_create.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{super()}} | New Task {% endblock %}

{% block body %}
{% block content %}
{{ navbar(current_user) }}
<div class="container">
    <br><br>
    <h1 class="h1 fs-3">New task</h1>
    <div class="p-2 flex-grow-1">
        {{ render_form(task_form, method='post', action=url_for('tasks.create_task', list_id=list.id)) }}
    </div>
</div>
{% endblock %}
{% endblock %}

app/templates/task_retrieve.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'macros.html' import navbar %}

{% block title %} {{super()}} | Task retrieve {% endblock %}

{% block body %}
{% block content %}
{{ navbar(current_user) }}
<div class="container">
    <br><br>
    <h1 class="h1 fs-3">Task details</h1>
    <div class="p-2 flex-grow-1">
        {{ render_form(task_form, method='post', action=url_for('tasks.retrieve_task', list_id=list.id,
        task_id=task.id)) }}
    </div>
</div>
{% endblock %}
{% endblock %}